'use strict';
/* ---------------------------------------------------------------------------
   Numeric floor: 3x3 helpers, a sym6 covariance inverse, the affine fixed
   point solve, Oklch to linear sRGB, super Gaussian kernel constants. Sorts
   first into the bundle, so nothing here references a later file. Affine maps
   push Gaussians forward exactly, w(x) = Ax + b sends N(mu, S) to
   N(A mu + b, A S A^T), so the IFS tree is its own level of detail hierarchy;
   terrain height is its own distance estimate, so zoom shrinks both scales.
   --------------------------------------------------------------------------- */

/* ========================== linear algebra (f64) ========================== */
// 3x3 matrices are row-major Float64Array(9), covariances sym6 in the order
// [xx, xy, xz, yy, yz, zz]. f64 here, narrowed to f32 at upload. In the two
// products below `out` may alias a, never b; mat3Vec's out may alias v.

function mat3Mul(a, b, out) {
  const o = out || new Float64Array(9);
  for (let r = 0; r < 3; r++) {
    const a0 = a[r * 3], a1 = a[r * 3 + 1], a2 = a[r * 3 + 2];
    o[r * 3]     = a0 * b[0] + a1 * b[3] + a2 * b[6];
    o[r * 3 + 1] = a0 * b[1] + a1 * b[4] + a2 * b[7];
    o[r * 3 + 2] = a0 * b[2] + a1 * b[5] + a2 * b[8];
  }
  return o;
}

// a * b^T. Carries the cut's own frame to the eye across a rebase.
function mat3MulT(a, b, out) {
  const o = out || new Float64Array(9);
  for (let r = 0; r < 3; r++) {
    const a0 = a[r * 3], a1 = a[r * 3 + 1], a2 = a[r * 3 + 2];
    o[r * 3]     = a0 * b[0] + a1 * b[1] + a2 * b[2];
    o[r * 3 + 1] = a0 * b[3] + a1 * b[4] + a2 * b[5];
    o[r * 3 + 2] = a0 * b[6] + a1 * b[7] + a2 * b[8];
  }
  return o;
}

function mat3Vec(a, v, out) {
  const o = out || new Float64Array(3);
  const x = v[0], y = v[1], z = v[2];
  o[0] = a[0] * x + a[1] * y + a[2] * z;
  o[1] = a[3] * x + a[4] * y + a[5] * z;
  o[2] = a[6] * x + a[7] * y + a[8] * z;
  return o;
}

// Rodrigues rotation about (ax, ay, az); the angle is in degrees.
function rotAxis(ax, ay, az, deg) {
  const n = Math.hypot(ax, ay, az) || 1;
  const x = ax / n, y = ay / n, z = az / n;
  const t = deg * Math.PI / 180, c = Math.cos(t), s = Math.sin(t), k = 1 - c;
  return new Float64Array([
    c + x * x * k,     x * y * k - z * s, x * z * k + y * s,
    y * x * k + z * s, c + y * y * k,     y * z * k - x * s,
    z * x * k - y * s, z * y * k + x * s, c + z * z * k,
  ]);
}

// Inverse of a symmetric 3x3 held as sym6, returned as sym6. Null if singular;
// the absolute 1e-300 test works because callers pass root covariances at unit scale.
function sym3Inv(s) {
  const s0 = s[0], s1 = s[1], s2 = s[2], s3 = s[3], s4 = s[4], s5 = s[5];
  const c00 = s3 * s5 - s4 * s4;
  const c01 = s4 * s2 - s1 * s5;
  const c02 = s1 * s4 - s3 * s2;
  const det = s0 * c00 + s1 * c01 + s2 * c02;
  if (!isFinite(det) || Math.abs(det) < 1e-300) return null;
  const id = 1 / det;
  return new Float64Array([
    c00 * id, c01 * id, c02 * id,
    (s0 * s5 - s2 * s2) * id, (s1 * s2 - s0 * s4) * id, (s0 * s3 - s1 * s1) * id,
  ]);
}

function det3(a) {
  return a[0] * (a[4] * a[8] - a[5] * a[7]) -
         a[1] * (a[3] * a[8] - a[5] * a[6]) +
         a[2] * (a[3] * a[7] - a[4] * a[6]);
}

// Solve (I - A) x = b by Gauss Jordan with partial pivoting. That x is the fixed
// point of w(x) = Ax + b and, for a contraction, lies exactly on the attractor.
// The absolute 1e-14 pivot floor holds because callers pass contractions.
function solveFixedPoint(A, b) {
  const m = [
    [1 - A[0], -A[1], -A[2], b[0]],
    [-A[3], 1 - A[4], -A[5], b[1]],
    [-A[6], -A[7], 1 - A[8], b[2]],
  ];
  for (let c = 0; c < 3; c++) {
    let piv = c;
    for (let r = c + 1; r < 3; r++) if (Math.abs(m[r][c]) > Math.abs(m[piv][c])) piv = r;
    if (Math.abs(m[piv][c]) < 1e-14) return null;
    const t = m[c]; m[c] = m[piv]; m[piv] = t;
    for (let r = 0; r < 3; r++) {
      if (r === c) continue;
      const f = m[r][c] / m[c][c];
      for (let k = c; k < 4; k++) m[r][k] -= f * m[c][k];
    }
  }
  return [m[0][3] / m[0][0], m[1][3] / m[1][1], m[2][3] / m[2][2]];
}

/* ================================ colour ================================= */
// Oklab (Ottosson 2020), a cube root LMS space fitted so a straight line in it
// reads straight to the eye. The ramp is generated by formula, which needs such
// a space: in HSV the same formula gives yellows twice as bright as its blues.
function oklabToLinear(L, a, b) {
  const l_ = L + 0.3963377774 * a + 0.2158037573 * b;
  const m_ = L - 0.1055613458 * a - 0.0638541728 * b;
  const s_ = L - 0.0894841775 * a - 1.2914855480 * b;
  const l = l_ * l_ * l_, m = m_ * m_ * m_, s = s_ * s_ * s_;
  return [4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
         -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
         -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s];
}
function inGamut(c) {                         // linear sRGB in [0, 1], slop 1e-4
  return c[0] >= -1e-4 && c[1] >= -1e-4 && c[2] >= -1e-4 &&
         c[0] <= 1.0001 && c[1] <= 1.0001 && c[2] <= 1.0001;
}
// Oklch to linear sRGB. Out of gamut the chroma gives way and never the channels:
// per channel clipping holds the requested lightness and shifts the hue, so a ramp
// gets hue plateaus wherever it asks for more chroma than the display has. The 24
// bisections of C at fixed L and h hold hue exactly and resolve C to about 1e-7.
function oklchToRgb(L, C, hdeg) {
  const h = hdeg * Math.PI / 180, ch = Math.cos(h), sh = Math.sin(h);
  let lo = 0;
  if (inGamut(oklabToLinear(L, C * ch, C * sh))) lo = C;
  else {
    let hi = C;
    for (let k = 0; k < 24; k++) {
      const m = 0.5 * (lo + hi);
      if (inGamut(oklabToLinear(L, m * ch, m * sh))) lo = m; else hi = m;
    }
  }
  const c = oklabToLinear(L, lo * ch, lo * sh);
  for (let i = 0; i < 3; i++) c[i] = c[i] < 0 ? 0 : (c[i] > 1 ? 1 : c[i]);
  return c;
}

/* ============================ the splat kernel =========================== */
// The rendered footprint is a super Gaussian,
//
//     k(x) = exp(-0.5 * (s * q)^(beta/2)),      q = x^T Sigma2D^-1 x
//
// beta = 2 is the ordinary Gaussian. Higher beta flattens the top and steepens
// the shoulder, closer to a fractal measure restricted to one compactly supported
// piece: flat over the piece, zero outside. kernelConst fixes s so the second
// moment stays Sigma2D, so beta changes shape and never scale.

function gammaFn(x) {
  // Lanczos, g = 7; the table and the 7.5 offset go together. Args are 2/beta and
  // 4/beta, so 0.25 to 3.33 over the clamped beta range.
  const g = [0.99999999999980993, 676.5203681218851, -1259.1392167224028,
    771.32342877765313, -176.61502916214059, 12.507343278686905,
    -0.13857109526572012, 9.9843695780195716e-6, 1.5056327351493116e-7];
  if (x < 0.5) return Math.PI / (Math.sin(Math.PI * x) * gammaFn(1 - x));
  x -= 1;
  let a = g[0];
  const t = x + 7.5;
  for (let i = 1; i < 9; i++) a += g[i] / (x + i);
  return Math.sqrt(2 * Math.PI) * Math.pow(t, x + 0.5) * Math.exp(-t) * a;
}

// For exp(-0.5 r^beta) in the plane, integral of r^k dr = 2^((k+1)/beta) / beta
// * Gamma((k+1)/beta). K below is the k = 1 case, the area factor; m2 is k = 3
// over k = 1, the mean square radius.
function kernelConst(beta) {
  const b = Math.max(1.2, Math.min(8, beta));  // 2/b and 4/b inside gammaFn's fit
  const K = Math.pow(2, 2 / b) * gammaFn(2 / b) / b;
  const m2 = Math.pow(2, 2 / b) * gammaFn(4 / b) / gammaFn(2 / b);
  const shape = m2 / 2;                       // so E[q] = 2, as for a Gaussian
  const rcut = Math.pow(13.8, 1 / b);         // 2*6.9, kernel at 1e-3; tracks the
                                              // shader's `e > 6.91` discard
  return {
    beta: b,
    shape,
    knorm: shape / (2 * Math.PI * K),         // peak = w * gain * knorm / sqrt(det)
    extent: rcut / Math.sqrt(shape),          // quad half size, in sigma
  };
}
